/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 JellyfishT.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/JellyfishT.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Moon_Jellyfish">
          <group name="Armature001_12" position={[1.936, 2.791, -1.539]} rotation={[0.426, -0.505, 0.317]} scale={0.642}>
            <group name="GLTF_created_1">
              <primitive object={nodes.Bone_9} />
              <primitive object={nodes.Bone001_10} />
              <skinnedMesh name="_gltfNode_7" geometry={nodes._gltfNode_7.geometry} material={materials['Material.003']} skeleton={nodes._gltfNode_7.skeleton} />
              <skinnedMesh name="_gltfNode_8" geometry={nodes._gltfNode_8.geometry} material={materials['Material.002']} skeleton={nodes._gltfNode_8.skeleton} />
              <skinnedMesh name="_gltfNode_9" geometry={nodes._gltfNode_9.geometry} material={materials['Material.001']} skeleton={nodes._gltfNode_9.skeleton} />
            </group>
          </group>
          <group name="Armature002_16" position={[-0.739, 3.856, 2.031]} rotation={[3.005, -0.549, -2.899]} scale={0.642}>
            <group name="GLTF_created_2">
              <primitive object={nodes.Bone_13} />
              <primitive object={nodes.Bone001_14} />
              <skinnedMesh name="_gltfNode_14" geometry={nodes._gltfNode_14.geometry} material={materials['Material.003']} skeleton={nodes._gltfNode_14.skeleton} />
              <skinnedMesh name="_gltfNode_15" geometry={nodes._gltfNode_15.geometry} material={materials['Material.002']} skeleton={nodes._gltfNode_15.skeleton} />
              <skinnedMesh name="_gltfNode_16" geometry={nodes._gltfNode_16.geometry} material={materials['Material.001']} skeleton={nodes._gltfNode_16.skeleton} />
            </group>
          </group>
          <group name="Armature003_20" position={[1.637, 5.766, -1.179]} rotation={[-2.941, -0.5, 2.963]} scale={0.642}>
            <group name="GLTF_created_3">
              <primitive object={nodes.Bone_17} />
              <primitive object={nodes.Bone001_18} />
              <skinnedMesh name="_gltfNode_21" geometry={nodes._gltfNode_21.geometry} material={materials['Material.003']} skeleton={nodes._gltfNode_21.skeleton} />
              <skinnedMesh name="_gltfNode_22" geometry={nodes._gltfNode_22.geometry} material={materials['Material.002']} skeleton={nodes._gltfNode_22.skeleton} />
              <skinnedMesh name="_gltfNode_23" geometry={nodes._gltfNode_23.geometry} material={materials['Material.001']} skeleton={nodes._gltfNode_23.skeleton} />
            </group>
          </group>
          <group name="Armature004_24" position={[-2.712, 2.349, -1.128]} rotation={[-2.836, -0.306, -2.573]} scale={0.812}>
            <group name="GLTF_created_4">
              <primitive object={nodes.Bone_21} />
              <primitive object={nodes.Bone001_22} />
              <skinnedMesh name="_gltfNode_28" geometry={nodes._gltfNode_28.geometry} material={materials['Material.003']} skeleton={nodes._gltfNode_28.skeleton} />
              <skinnedMesh name="_gltfNode_29" geometry={nodes._gltfNode_29.geometry} material={materials['Material.002']} skeleton={nodes._gltfNode_29.skeleton} />
              <skinnedMesh name="_gltfNode_30" geometry={nodes._gltfNode_30.geometry} material={materials['Material.001']} skeleton={nodes._gltfNode_30.skeleton} />
            </group>
          </group>
          <group name="Armature005_28" position={[2.578, 1.887, 3.183]} rotation={[-0.774, 0.582, 0.534]} scale={0.572}>
            <group name="GLTF_created_5">
              <primitive object={nodes.Bone_25} />
              <primitive object={nodes.Bone001_26} />
              <skinnedMesh name="_gltfNode_35" geometry={nodes._gltfNode_35.geometry} material={materials['Material.003']} skeleton={nodes._gltfNode_35.skeleton} />
              <skinnedMesh name="_gltfNode_36" geometry={nodes._gltfNode_36.geometry} material={materials['Material.002']} skeleton={nodes._gltfNode_36.skeleton} />
              <skinnedMesh name="_gltfNode_37" geometry={nodes._gltfNode_37.geometry} material={materials['Material.001']} skeleton={nodes._gltfNode_37.skeleton} />
            </group>
          </group>
          <group name="Armature006_32" position={[2.537, 1.04, -3.032]} rotation={[-3.007, 0.52, 2.786]} scale={[0.405, 0.275, 0.405]}>
            <group name="GLTF_created_6">
              <primitive object={nodes.Bone_29} />
              <primitive object={nodes.Bone001_30} />
              <skinnedMesh name="_gltfNode_42" geometry={nodes._gltfNode_42.geometry} material={materials['Material.003']} skeleton={nodes._gltfNode_42.skeleton} />
              <skinnedMesh name="_gltfNode_43" geometry={nodes._gltfNode_43.geometry} material={materials['Material.002']} skeleton={nodes._gltfNode_43.skeleton} />
              <skinnedMesh name="_gltfNode_44" geometry={nodes._gltfNode_44.geometry} material={materials['Material.001']} skeleton={nodes._gltfNode_44.skeleton} />
            </group>
          </group>
          <group name="Armature007_36" position={[0.647, 3.988, 0.323]} rotation={[-3.064, 0.514, 3.022]} scale={[0.262, 0.28, 0.264]}>
            <group name="GLTF_created_7">
              <primitive object={nodes.Bone_33} />
              <primitive object={nodes.Bone001_34} />
              <skinnedMesh name="_gltfNode_49" geometry={nodes._gltfNode_49.geometry} material={materials['Material.003']} skeleton={nodes._gltfNode_49.skeleton} />
              <skinnedMesh name="_gltfNode_50" geometry={nodes._gltfNode_50.geometry} material={materials['Material.002']} skeleton={nodes._gltfNode_50.skeleton} />
              <skinnedMesh name="_gltfNode_51" geometry={nodes._gltfNode_51.geometry} material={materials['Material.001']} skeleton={nodes._gltfNode_51.skeleton} />
            </group>
          </group>
          <group name="Armature_8" position={[0.013, 0.049, -0.074]} rotation={[0.168, 0, 0]} scale={0.842}>
            <group name="GLTF_created_0">
              <primitive object={nodes.Bone_5} />
              <primitive object={nodes.Bone001_6} />
              <skinnedMesh name="_gltfNode_0" geometry={nodes._gltfNode_0.geometry} material={materials['Material.003']} skeleton={nodes._gltfNode_0.skeleton} />
              <skinnedMesh name="_gltfNode_1" geometry={nodes._gltfNode_1.geometry} material={materials['Material.002']} skeleton={nodes._gltfNode_1.skeleton} />
              <skinnedMesh name="_gltfNode_2" geometry={nodes._gltfNode_2.geometry} material={materials['Material.001']} skeleton={nodes._gltfNode_2.skeleton} />
            </group>
          </group>
          <group name="Sphere001_38" position={[2.826, 3.371, -0.551]} scale={0.041}>
            <mesh name="_gltfNode_58" geometry={nodes._gltfNode_58.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere002_39" position={[3.364, 6.844, 0.752]} scale={0.029}>
            <mesh name="_gltfNode_60" geometry={nodes._gltfNode_60.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere003_40" position={[3.235, 1.009, 2.897]} scale={0.029}>
            <mesh name="_gltfNode_62" geometry={nodes._gltfNode_62.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere004_41" position={[0.002, 2.506, 4.201]} scale={0.029}>
            <mesh name="_gltfNode_64" geometry={nodes._gltfNode_64.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere005_42" position={[-3.675, 0.899, 2.751]} scale={0.029}>
            <mesh name="_gltfNode_66" geometry={nodes._gltfNode_66.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere006_43" position={[-2.366, 6.042, -2.977]} scale={0.029}>
            <mesh name="_gltfNode_68" geometry={nodes._gltfNode_68.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere007_44" position={[3.158, 3.821, -3.137]} scale={0.029}>
            <mesh name="_gltfNode_70" geometry={nodes._gltfNode_70.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere008_45" position={[2.781, 0.521, -1.589]} scale={0.029}>
            <mesh name="_gltfNode_72" geometry={nodes._gltfNode_72.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere009_46" position={[2.161, 3.718, 0.45]} scale={0.029}>
            <mesh name="_gltfNode_74" geometry={nodes._gltfNode_74.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere010_47" position={[2.341, -0.02, -2.474]} scale={0.029}>
            <mesh name="_gltfNode_76" geometry={nodes._gltfNode_76.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere011_48" position={[1.601, 4.386, -0.982]} scale={0.029}>
            <mesh name="_gltfNode_78" geometry={nodes._gltfNode_78.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere012_49" position={[-0.878, 7.008, 0.056]} scale={0.029}>
            <mesh name="_gltfNode_80" geometry={nodes._gltfNode_80.geometry} material={materials['Material.004']} />
          </group>
          <group name="Sphere_37" position={[-1.352, 3.043, -2.817]} scale={0.041}>
            <mesh name="_gltfNode_56" geometry={nodes._gltfNode_56.geometry} material={materials['Material.004']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/JellyfishT.glb')
